---
title: "Bank: Establish a global banking partnership"
output: html_document
---
<head>
<script language = "javascript">
<!--hide
var password;
var pass1="12345";
password=prompt('Enter Password To View Page',' ');
if (password==pass1)
alert ('Correct password, click OK to enter.';
else
{window.location="http://www.chrielben.github.io";
}
//-->
</script>
</head>
<style>
p.comment {
background-color: #f49800;
padding: 10px;
border: 1px solid black;
margin-left: 25px;
border-radius: 5px;
font-style: ;
}

p.status {
background-color: #f49800;
padding: 10px;
border: 1px solid black;
margin-left: 25px;
border-radius: 5px;
font-style: ;
}
</style>

<p class="comment">
<b> Required departments </b> Internal: Global Finance
</p>

<p class="comment">
<b> Project approved by </b> Not approved
</p>

<p class="comment">
<b> Expected cost </b> TBD
</p>

<p class="comment">
<b> Priority </b> TBD
</p>

<p class="comment">
<b> Budget approved by </b> Not Approved
</p>

<p class="comment">
<b> Project Status </b> Not initiated
</p>

<p class="comment">
<b> Project Description </b>
This project aims to collect all banking agreements outside the markets that Danske Bank serves (Nordic + DE + UK + IE) in one new banking agreement to reduce banking cost, to lower the cost of enabling the Continia banking add-ins in NAV, to have requested banking services provided, to be able to enable a dual approval payment flow as we know from Danske Bank, to reduce amount of banking platforms to two (Danske Bank + the new bank), and to have a single account manager to contact when changes needs to be made to ensure a more quickly process of changes to the rendered services by the bank.
</p>

<p class="comment">
<b> Project Goal </b>
One bank which provides a local currency account and a USD denomited account for all entities (Australia, China, Hong Kong, United Arab Emirates, Turkey, South Africa, Spain, Brazil and USA). Ability to issue credit cards from Australia, Hong Kong and United Arab Emirates and further the ability yo enable the service in other regions in the future. To be able to make all types of payments from all companies incl. but not limited to domestic payments, international payments, recurring payments, issueing cheques. To be able to look through all group accounts in one platform like Danske Banks District. To be able to able to export transactions preferably through webservice but otherwise as a .csv or .txt file format that can be used to import transactions into NAV. To be able to export credit card transactions to NAV and automatically asign transactions to users in expense management if enabled in NAV. To lower the total banking cost by hopefully being presented with a cost structure with lower transaction costs as a result of economies of scale by combining all subsidiaries in one banking agreement.
</p>

<p class="status">
<b>29-04-2020</b>
Project created
</p>