---
title: "Bank: Apply for GBP denominated account with Danske Bank"
output: html_document
---
<head>
<script language = "javascript">
<!--hide
var password;
var pass1="12345";
password=prompt('Enter Password To View Page',' ');
if (password==pass1)
alert ('Correct password, click OK to enter.';
else
{window.location="http://www.chrielben.github.io";
}
//-->
</script>
</head>
<style>
p.comment {
background-color: #f49800;
padding: 10px;
border: 1px solid black;
margin-left: 25px;
border-radius: 5px;
font-style: ;
}

p.status {
background-color: #f49800;
padding: 10px;
border: 1px solid black;
margin-left: 25px;
border-radius: 5px;
font-style: ;
}
</style>

<p class="comment">
<b> Required departments </b> Internal: Global Finance
</p>

<p class="comment">
<b> Project approved by </b> Karsten Ehlig Petersen
</p>

<p class="comment">
<b> Expected cost </b> DKK 8,000
</p>

<p class="comment">
<b> Priority </b> TBD
</p>

<p class="comment">
<b> Budget approved by </b> Karsten Ehlig Petersen
</p>

<p class="comment">
<b> Project Status </b> Awaiting Danske Bank
</p>

<p class="comment">
<b> Project Description </b>
The aim of the project is to add a bank account denominated in GBP located with the Danske Bank London office. The bank account is to be used for payments of UK based customers who are invoices in GBP, payment of vendors who invoices in GBP and payment of employees who receives their salary in GBP.
</p>

<p class="comment">
<b> Project Goal </b>
After the project is implemented it will make: 1. payment of vendors and employees in the UK more quickly because we can arrange payments domesticly, 2. The workflow of arranging payments to UK vendors more efficient because we can enable the continia payment management add-in to NAV, and 3. avoid revisiting bookings of payments after payment has been deducted from the bank account to get the exchange rate applied to the payment.
</p>

<p class="status">
<b>27-04-2020</b>
Currently we have been asked to complete two tasks by Danske Bank for them to create the account: 1) complete a Know your Customer (KYC) review and 2) fill out and sign a number of documents. The KYC review was resubmitted to Danske Bank because the Tax Complience Form had been filled out for JBH - they wanted one submitted for Panzerglass - and asked for a signed group structure incl. individual owners with more than 10% ownership of Panzerglass A/S. Regarding the second task: All documents have been signed, but before we can submit the applcation all individuals who have signed one or more documents have to be verified by our account manager at Danske Bank. Copies of passports or drivers licences have been sent to our account manager today such that he can create the requested statement. All documents can then be sent along with his statement via mail to Danske Bank London, and they should be able to open an account when they have verified the documentation.
</p>

<p class="status">
<b>27-04-2020</b>
All documents regarding the KYC has been submitted through Danske Banks District platform. We are awaiting a responce from them to close the task.
</p>

<p class="status">
<b>28-04-2020</b>
Our Danske Bank account manager - Jan Tholstrup Bomholdt - have signed all documents regarding verification of identities and addresses today. Next step is to mail the application to Danske Bank London via post, but before doing so Karsten Ehlig Petersen has promissed to look through the documents to verify that everything is correct - applying the four eyes principle, when he has done so the application will be posted.
</p>

<p class="status">
<b>28-04-2020</b>
Status updated to awaiting KAPE
</p>

<p class="status">
<b>29-04-2020</b>
KArsten Ehlig Petersen has looked through the documents and approved them, besides opting in to the Danske Bank leasing module. The document has been modified to opting out of the leasing agreement. The documents has been handed over to Mikael Pedersen to post from the warehouse. He has promissed to send the letter with tracking. We will receive the tracking number once available.
</p>

<p class="status">
<b>29-04-2020</b>
Status updated to awaiting MIPE
</p>

<p class="status">
<b>29-04-2020</b>
The contract has been posted with DHL with tracking number 3887696422. The expected delivery date is tommorrow, 30-04-2020.
</p>

<p class="status">
<b>29-04-2020</b>
Status updated to awaiting Danske Bank
</p>